name: devla_request
description: http client request for dart with interceptor integrate ( BaseURL, RefreshToken when Token expired, etc...).
version: 0.0.1
author: Vongkeo KEOSAVANH
homepage: https://github.com/DevlaMediaProduct/devla_request

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  get: ^3.17.1
  get_storage: ^1.3.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: